### ISSUE TITLE
yougather.xyz login problems: Server Error (500)

### ISSUE THREAD

**Issue by SidGauVic** [Elijas/auto-youtube-subscription-playlist-2#10]
For the most part, yougather.xyz has been working phenomenally for me. Makes it super easy to watch a chronological list of subscriptions in the Watch Later list.

Recently, I noticed that videos were not being added. This came after I enabled 2 factor authentication. I've tried logging into yougather.xyz, but all I get is "Server Error (500)". Clearing cache, using a different computer, using incognito (on chrome), using a different browser does not resolve anything.

Any suggestions going forward? For now I've reverted to using the script + google sheets.

**Comment by Remco32** [comment]
Can confirm this.

**Comment by Elijas** [comment]
Our server reached usage limits, we currently don't have a way to sustainably support it financially.

Maybe, sometime in the future it will be migrated to my other server and a freemium model will be provided to support it.

Until then, google scripts are the available option.

Any suggestions welcome!:)
