### ISSUE TITLE
I want to add videos from earlier?

### ISSUE THREAD

**Issue by dogeatdogeatdog** [Elijas/auto-youtube-subscription-playlist-2#101]
I want to add videos from every day in the last week, I tried changing the timestamp from "2021-10-07T18:13:49+02:00" to  "2021-10-06T18:13:49+02:00" but it gave me this error
"Error: 2 video(s) were not added to playlists correctly, please check Debug sheet. Timestamps for respective rows has not been updated."

**Comment by victorjzsun** [comment]
I made the new version at https://github.com/Elijas/auto-youtube-subscription-playlist-2/blob/1-day-update/sheetScript.gs, copy the script into Tools -> Script Editor and you can then run it normally.

P.S. The debug sheet was actually broken, must've accidentally deleted the function call; try copying the new sheet into your spreadsheet if you want the new version.
