### ISSUE TITLE
Scheduling menu changes

### ISSUE THREAD

**Issue by erfg12** [Elijas/auto-youtube-subscription-playlist-2#103]
To schedule the `updatePlaylists` function, it's under different menus now.

Go to `Extensions` / `Apps Script` then press the blue button in the lower right corner `+ Add Trigger`. By default the `updatePlaylist` function should be highlighted. Change the `Select Event Source` to `Time-driven` and save.

**Comment by victorjzsun** [comment]
Thanks for the update, made changes to the README.
