### ISSUE TITLE
No license?

### ISSUE THREAD

**Issue by MaySoMusician** [Elijas/auto-youtube-subscription-playlist-2#105]
I'm thinking to start a web service similar to this, but *hosted* one (i.e. users don't need to create their own google apps script project), and I found here. Unfortunately there is no license information in this repository at the moment. They just forgot to add LICENSE file, or have made the code unlicensed to keep all rights reserved? (the author must explicitly give a permission to make a project open source)
I would be super happy if you marked the project as open source (MIT, MPL, or evil GPL?). But I don't request it so strongly, because it may look like I took your copyrights for my business if I did...

**Comment by victorjzsun** [comment]
@Elijas what do you think, I'm not good with licenses and such

**Comment by Elijas** [comment]
@victorjzsun MIT license would basically allow anyone to use our code for anything (including selling it), as long as they include your name. If you agree, please approve the PR.

**Comment by Elijas** [comment]
@MaySoMusician It's now MIT. Cheers!;)
