### ISSUE TITLE
Unable to add video to Watch Later

### ISSUE THREAD

**Issue by EddieHaybell** [Elijas/auto-youtube-subscription-playlist-2#106]
Just like the title says. I tried to add videos to my Watch Later. It says it acquired some videos, but couldn't update Watch later or watch history because the functionality is deprecated. Any idea if this functionality was added and then removed at some point, and how to bring it back?

**Comment by victorjzsun** [comment]
Please reference this post: https://stackoverflow.com/questions/66156461/unable-to-insert-video-into-the-watch-later-wl-playlist/66157183#66157183. It is depreciated since 2020 and until YouTube brings the functionality back, there's nothing we can do.

**Comment by EddieHaybell** [comment]
Right, thanks. Since nothing can be done, I'll be closing this.
