### ISSUE TITLE
Error: No empty spots

### ISSUE THREAD

**Issue by KnifeFed** [Elijas/auto-youtube-subscription-playlist-2#110]
![CleanShot (CleanShot) - 2022-04-05 at 14 57 05@2x](https://user-images.githubusercontent.com/85502276/161758848-5610911e-4b66-417d-a32a-a4146f212a23.png)

If the `No empty spots` error is thrown, the whole script fails, so I just realized I haven't had any videos added for days. I made a new copy of the sheet/script which fixed it.

**Comment by victorjzsun** [comment]
I just realized this is an edge case and will fix it. If you still have the sheet with the broken sheet, it’d be great if you could confirm something for me. Can you look at the last populated cell in the rightmost populated column of the DebugData sheet (might need to unhide the sheet) and tell me its row and column number?

**Comment by KnifeFed** [comment]
If I understood you correctly, it's cell `Z935` and contains `Updated all rows, script successfully finished`.

**Comment by victorjzsun** [comment]
I've updated the original sheet and the GitHub code, try using the new version and let me know if you still run into any issues.
