### ISSUE TITLE
Time Based Trigger No Longer Working

### ISSUE THREAD

**Issue by Jelbrekinator** [Elijas/auto-youtube-subscription-playlist-2#111]
The script has worked flawlessly for me for over a year but now the time based trigger has stopped working, I can adjust the time and manually trigger the script to add videos but no longer automatically via time based trigger, I have made no changes, it just suddenly stopped updating

I get the following error: Error: 2 video(s) were not added to playlists correctly, please check Debug sheet. Timestamps for respective rows has not been updated.
    at updatePlaylists(Code:199:11)

**Comment by victorjzsun** [comment]
That means that the script has run into an error. Can you go to the Debug sheet and tell me what it says? It should look something like this:
![image](https://user-images.githubusercontent.com/17478849/162586017-bcb3eae9-adfb-4d69-8c02-8ded6901be9b.png)

**Comment by victorjzsun** [comment]
I don't see any error for that particular execution. Were there any logs for the error in the original issue post? Also, the debug sheet looks like the trigger is still firing every hour and I don't see any manual executions. Could you describe in more detail how you run it manually and perhaps the different debug logs for the manual execution and trigger execution?

**Comment by victorjzsun** [comment]
@Jelbrekinator can you provide an update? if this issue is no longer relevant, I'll close this issue

**Comment by Jelbrekinator** [comment]
Apologies, not sure what the issue was but it’s working as intended now
