### ISSUE TITLE
TypeError: Cannot read property '1' of undefined

### ISSUE THREAD

**Issue by JasonDerulo1259** [Elijas/auto-youtube-subscription-playlist-2#114]
Keep getting the error message
`TypeError: Cannot read property '1' of undefined`
When running the script, haven't even been able to make the initial update yet.

**This is how the spreadsheet is set up rn**

![image](https://user-images.githubusercontent.com/71148978/168915245-ab78aa1c-059c-462f-9f37-18605370c9b8.png)

**Comment by TheDunco** [comment]
I am seeing this issue as well! Hopefully these images can help...

<img width="565" alt="Screen Shot 2022-05-17 at 10 49 19 PM" src="https://user-images.githubusercontent.com/44826828/168947061-e85c2178-9fc5-4ffd-b4ba-5d78275e7289.png">

<img width="698" alt="Screen Shot 2022-05-17 at 10 50 19 PM" src="https://user-images.githubusercontent.com/44826828/168947168-62ccf6d5-a798-4f16-878e-c42b323d6ea3.png">

Thanks!

**Comment by victorjzsun** [comment]
API must have been changed or something, empty sheet now has different values, working on fix rn

**Comment by victorjzsun** [comment]
Should be fixed now, make a new copy of the script or copy `sheetScript.gs` to the script editor

**Comment by NotSoHeroic** [comment]
> API must have been changed or something, empty sheet now has different values, working on fix rn

I believe there is a similar issue with the  [removeVidsFromPlaylist.md's](https://github.com/Elijas/auto-youtube-subscription-playlist-2/blob/master/removeVidsFromPlaylist.md) scripts. They suddenly have stopped working for me. Anyway we can get a fix?

**Comment by victorjzsun** [comment]
> I believe there is a similar issue with the [removeVidsFromPlaylist.md's](https://github.com/Elijas/auto-youtube-subscription-playlist-2/blob/master/removeVidsFromPlaylist.md) scripts. They suddenly have stopped working for me. Anyway we can get a fix?

Should be fixed now

**Comment by victorjzsun** [comment]
Given that this problem has been fixed, I'll be closing this issue. If needed, please reopen
