### ISSUE TITLE
3 seperate youtube accounts deleted for spam using this script?

### ISSUE THREAD

**Issue by digyan** [Elijas/auto-youtube-subscription-playlist-2#116]
Hello, TLDR is I've had 3 seperate youtube channels with common denominator of using this script deleted for:

>Spam, scams or commercially deceptive content are not allowed on YouTube.

All accounts were used only for viewing videos, no uploads/comments etc.

Two of which were being charged and continues to be charged for Youtube Premium which I can't cancel since deleting channel locks out of youtube premium management page (lol). I think I'm going to have to cancel credit card to get that sorted. Third and final account didn't even bother with premium.

All  accounts also used sponsor block but as far as I can tell, others aren't losing their channels for using this extention. Appeal process so far has been useless.

First account used script for 1+ year without issue. Second and third were wiped within a couple months. I'm wondering if anyone has experienced anything similar?

**Comment by Fabian42** [comment]
I'm following the issues here for a while already and never heard of this, so it's probably caused by something else.

If you pay for something, cannot get the service in return and cannot cancel it, suing is always an option. You probably don't even have to go to court, just a lawyer writing an angry letter should do it.

**Comment by digyan** [comment]
> probably caused by something else.

I'll make a new google account and see if it happens again. All 3 banned accounts were multiple years old, accounts 2 and 3 were dormant on youtube until I migrated the sheet/script over before fast ban. Someone on r/youtube suggested it might be due to new youtube moves to crack on viewbot behaviour which this script might trigger. I'm wondering if there's something to it since first account that worked fine for 1+ year got canned shortly after making playlists unlisted/public (not private) to enable viewing on newpipe. Accounts 2&3 were made unlisted from the go so I could still access from 1st acount on chrome. I have no idea, maybe something on my computer, but I did fresh reformat and OS install after 2nd account banned just in case. It's just very puzzling. No one else on house IP has issues with their account either.

As for suing, I have too much data still backed up on Google right now to risk anything. Going through useless appeal process is doing nothing, gets automatically upheld within hours of appeal. I should add, I had Google One on the first account and contacted in person support who forwarded issue to YT team and was given the very unhelpful reply that "they weren't equipped to deal with the issue". Doing a big data takeout out now before trying to get a new credit card and hopefully pay future Google One on gift cards.

**Comment by lucienve** [comment]
It might be worth seeing whether your use of 'newpipe' (which circumvents
the YouTube viewer and advertisement tracking) might be the real cause of
the bans, instead of the use of one of the officially supported YouTube
API's called from within a Google Sheet.

**Comment by victorjzsun** [comment]
Echoing what others have said, this should not be an issue with this script as we are using Google's published APIs. Will close as unrelated
