### ISSUE TITLE
Delete old videos option not working

### ISSUE THREAD

**Issue by Ehan13** [Elijas/auto-youtube-subscription-playlist-2#117]
The setup gives the option to delete old videos by inserting a number in the grey column (states column B in the writing, but I’m assuming it was moved to column E in newer versions). This feature doesn’t appear to be working. Has anyone else gotten this to work?

Photos attached
![A4392BD1-CA7F-45B1-ACD7-BF576BBD9A5C](https://user-images.githubusercontent.com/93287556/187775378-5102bf5c-214d-477a-9147-f6a1f3d54224.jpeg)
![3391045D-9F3E-470A-A081-A1448C6B7D02](https://user-images.githubusercontent.com/93287556/187775387-ed3a48d2-fe8e-411e-b68d-9722a8298b57.jpeg)

**Comment by victorjzsun** [comment]
Looks like the README is still outdated, the correct column is column D, not E

**Comment by Ehan13** [comment]
I actually tried adding a number to column D instead of E. I added a “1” to signify to delete anything older than one day. 

Adding anything to column D appears to stop the entire automation from working at all. Once I delete the number from column D, the automation works again. 

Do you find that to be the issue also?

**Comment by victorjzsun** [comment]
I just tried it and it worked for me, what do you mean by the entire automation doesn’t work anymore? Does the script run but not do anything? What shows up in the debug logs?

**Comment by Ehan13** [comment]
I just did a manual run with the number 2 added to column D. This is the entire debug log created. Thanks Victor!
![1DC7CFBF-117E-4F60-A8E6-65421D7C39AA](https://user-images.githubusercontent.com/93287556/188240066-194e599f-5396-47ae-8ebe-29c59c8d58c8.jpeg)
![86F93AF3-FA21-4B91-9050-E2B231519B36](https://user-images.githubusercontent.com/93287556/188240072-d86aaeb2-a0b2-4561-861e-4bb2335e9925.jpeg)
![FD2CE613-32AC-48D1-83AC-10722F8CE916](https://user-images.githubusercontent.com/93287556/188240077-03622c19-1ce1-492d-8077-0b9ae98b01a7.jpeg)

**Comment by victorjzsun** [comment]
Hm, that's kinda weird, you shouldn't be hitting your quota, inserting and deleting only take 50 each and you only insert/delete 9 videos before you hit the quota. All the other api calls are basically negligible. This is on a fresh run of the day right (didn't run the script earlier that day)?

**Comment by victorjzsun** [comment]
Hey @Ehan13 are you still running into this issue? Doesn't seem like anything is wrong with the script, you might've just run it too many times in one day

**Comment by Ehan13** [comment]
Hi. It works great now. Thank you for checking in!—Eric HanusaOn Dec 4, 2022, at 1:40 PM, Victor Sun ***@***.***> wrote:﻿
Hey @Ehan13 are you still running into this issue? Doesn't seem like anything is wrong with the script, you might've just run it too many times in one day

**Comment by victorjzsun** [comment]
Sounds good, closing this issue then
