### ISSUE TITLE
error adding videos

### ISSUE THREAD

**Issue by kurokirasama** [Elijas/auto-youtube-subscription-playlist-2#118]
Hello,

I've got this error in the debug sheet:
```
Channel UCRM_wkKqfwVB9OgayzdMEQQ does not have any uploads in UURM_wkKqfwVB9OgayzdMEQQ, Failed with error Message: [API call to youtube.playlistItems.list failed with error: The playlist identified with the request's <code>playlistId</code> parameter cannot be found.] Details: {"message":"The playlist identified with the request's <code>playlistId</code> parameter cannot be found.","code":404,"errors":[{"domain":"youtube.playlistItem","reason":"playlistNotFound","message":"The playlist identified with the request's <code>playlistId</code> parameter cannot be found.","locationType":"parameter","location":"playlistId"}]}
```

I already unsubscribed from that channel but the error persists

**Comment by victorjzsun** [comment]
Are you sure you don't have `UCRM_wkKqfwVB9OgayzdMEQQ` explicitly as one of the channels to check in the sheet?

**Comment by Fabian42** [comment]
Empty channels cause the script to fail BTW, it doesn't just skip them. So you cannot use this script to get notified if someone starts uploading videos.

**Comment by victorjzsun** [comment]
Really? I just ran it on my sheet using the above channel ID and it just logs it, no error. Are you using the up to date script? On line 343, you should have a log but not an `addError` call, as in [the current script](https://github.com/Elijas/auto-youtube-subscription-playlist-2/blob/master/sheetScript.gs#L343)

**Comment by Fabian42** [comment]
Oh, following the project still doesn't notify me about commits. Tried it with the latest version now and it does indeed work, but the output looks as if it didn't:

Channel UCAqzgFGOss0mFN0OUKkdqMw does not have any uploads in UUAqzgFGOss0mFN0OUKkdqMw, Failed with error Message: [API call to youtube.playlistItems.list failed with error: The playlist identified with the request's <code>playlistId</code> parameter cannot be found.] Details: {"code":404,"message":"The playlist identified with the request's <code>playlistId</code> parameter cannot be found.","errors":[{"message":"The playlist identified with the request's <code>playlistId</code> parameter cannot be found.","locationType":"parameter","reason":"playlistNotFound","location":"playlistId","domain":"youtube.playlistItem"}]}

"Failed", "error", "error", "errors", …

**Comment by victorjzsun** [comment]
Yeah, I gotta remember to make releases. I'll change the text to be less alarming...

**Comment by victorjzsun** [comment]
As far as I can tell, this is no longer an issue, so closing this. Please reopen if further improvement is needed.
