### ISSUE TITLE
option to get all old videos as well as new ones 

### ISSUE THREAD

**Issue by nextcode4u** [Elijas/auto-youtube-subscription-playlist-2#12]
Is there anyway to set an option to add all the videos from the channels ive entered into the playlist. I wish to run a playlist on the tv at my shop for customers, but id like it to add all the videos from the channels so i can put the playlist on random and repeat and it be able to play 24/7, but only adding new videos from the channels I've entered doesn't give me enough content to keep playing all day. 

If theres an edit to script i can do to make it do so please give me some feedback id really appreciate it. Im using google sheets for the playlist

**Comment by michalpawl** [comment]
If you're still looking for a solution to this:
You can edit the timestamp in the sheet (cell F1) and set it to some date far in the past. Then the script will add all the videos uploaded after that date (including ones that are already on your playlist so you're probably going to have to de-duplicate it).
