### ISSUE TITLE
Feature request: Exclude "shorts" respectively short videos not longer than x minutes/seconds

### ISSUE THREAD

**Issue by eatsmarter-benny** [Elijas/auto-youtube-subscription-playlist-2#120]
Do you know the situation that some of your favorite channels started adding those "soul-destroying" shorts and you have to waste so many mouse clicks to selectively delete those one by one by hand?

Would be great if you could subscribe to a channel or playlist and exclude fetching "shorts" or even better videos that are shorter than a number of seconds of your choosing.

**Comment by Deiwulf** [comment]
Was just about to suggest the same, the spam is getting out of hand.

**Comment by sk33ny** [comment]
I came here to suggest this feature, I'm glad I'm not the only one.

**Comment by Fabian42** [comment]
YouTube kind of added this feature:
![image](https://github.com/Elijas/auto-youtube-subscription-playlist-2/assets/10481506/c276aa1b-47f8-475e-ac55-efabfe0da2c6)
But it isn't saved.

**Comment by victorjzsun** [comment]
I've updated the sheet and code to have a new column to remove shorts from being added. Please [make a copy of the sheet](http://bit.ly/subscriptionPlaylistsCopy) again and try it out! Let me know if you encounter any issues.

**Comment by eatsmarter-benny** [comment]
> I've updated the sheet and code to have a new column to remove shorts from being added. It's not the best solution and will remove any videos less than 1 minute as well. Please [make a copy of the sheet](http://bit.ly/subscriptionPlaylistsCopy) again and try it out! Let me know if you encounter any issues.

Yes, thank you very much for that!
The core functionality works: Grabs all videos, filters shorts and throws them away before importing.
Am am grateful and happy about that ^_^


But I found a bug with the new Google Sheets file though:
On the Debug page, the Logs in column C do not update automatically anymore.
Field `C3` shows `#NAME?`
and the tooltip reads 
```
Error
Unknown function: 'getLogs'.
```

Just clicking onto the drop-down menu in `B3` on the same newest date is not enough but if you choose a different older date, then the function is get's re-triggered and the `getLogs` function is found again and runs.
After that you can choose the newest date again the the function also works with the newest date.

But if you open the sheet for the first time or reload the whole page, you run into the error state above with unknown function.

In the older sheet that never happened and the sheet always initializes the newest log with the newest date automatically.

**Comment by victorjzsun** [comment]
Hm, not sure about the exact cause, but played around with it; does it work now?

**Comment by eatsmarter-benny** [comment]
> Hm, not sure about the exact cause, but played around with it; does it work now?

No, the described behavior is still present in the Google document.

Do you have this problematic behavior? You just wrote that you "played with it" but not if you can reproduce the behavior on your end.

**Comment by davisjk** [comment]
I encountered a similar problem because I deleted the DebugData sheet and manually deleted everything below the 2nd row in the Debug sheet. It was causing the script to error out without doing anything tho, not just stop displaying logs like you're seeing. I had to re-copy the original sheet to fix my problem.

**Comment by eatsmarter-benny** [comment]
It's not about a missing DebugData sheet here with me. I made a fresh copy of the newest script and filled in everything by hand again.

But good news, it must have been a "Google thing" because it now works again. When I load the page from a link, bookmark or resume the errors propagate automatically again.
Maybe Google made changes behind the curtains and rolled those out gradually and now they reached my account too.
