### ISSUE TITLE
No New Videos for certain playlists

### ISSUE THREAD

**Issue by Rumik** [Elijas/auto-youtube-subscription-playlist-2#122]
Hi there,

for some reason, the script never finds any videos within the following playlists:

PLpg6WLs8kxGOE_SZoj-gfn8FHF0c8nJwi
PLpg6WLs8kxGNL5FL6lNys2rK-3lajF_F8
PLpg6WLs8kxGPB73jDtwbHZRXv9_x5pJvA
PLpg6WLs8kxGMgYb13XjPgOKbm5O-CDq7R
PLpg6WLs8kxGPqjtjJ6JPwrDPWfX5zst8_
PLpg6WLs8kxGMF97sTrMd67zjkaxG1OhUz

Playlist with id PLpg6WLs8kxGOE_SZoj-gfn8FHF0c8nJwi has no new videos 
Playlist with id PLpg6WLs8kxGNL5FL6lNys2rK-3lajF_F8 has no new videos
Playlist with id PLpg6WLs8kxGPB73jDtwbHZRXv9_x5pJvA has no new videos
Playlist with id PLpg6WLs8kxGMgYb13XjPgOKbm5O-CDq7R has no new videos
Playlist with id PLpg6WLs8kxGPqjtjJ6JPwrDPWfX5zst8_ has no new videos
Playlist with id PLpg6WLs8kxGMF97sTrMd67zjkaxG1OhUz has no new videos

Any ideas why this might be happening?

Thanks

**Comment by victorjzsun** [comment]
Have you had these playlists in your script for a long time already? The script will only add videos published after the timestamp in the spreadsheet. If you want to add previous videos, change the timestamp to be further into the past.

**Comment by Rumik** [comment]
No, that’s not the case. I delete the timestamps and still it finds nothing ☹

**Comment by Rumik** [comment]
Actually, please ignore me. I manually set the timestamp to like a month ago and it started working. Strange that it never worked until now, but I must have done something wrong.

Thanks
