### ISSUE TITLE
Can't update Watch Later

### ISSUE THREAD

**Issue by Eran-ARPalus** [Elijas/auto-youtube-subscription-playlist-2#126]
Two days in a row now, I've been unable to send new subscriptions to my Watch Later list. It says that option is deprecated. Is there some way to bypass it and get videos in anyway?

`Feb 4, 2024, 6:13:53 AM	Info	Row: 4
Feb 4, 2024, 6:13:54 AM	Info	Acquired subscriptions 97.0
Feb 4, 2024, 6:14:30 AM	Info	Acquired 56 videos
Feb 4, 2024, 6:14:42 AM	Info	Added 56 video(s) to playlist. Error for 0 video(s).
Feb 4, 2024, 6:14:44 AM	Info	Row: 5
Feb 4, 2024, 6:14:44 AM	Info	Acquired subscriptions 97.0
Feb 4, 2024, 6:15:15 AM	Info	Acquired 104 videos
Feb 4, 2024, 6:15:15 AM	Info	Couldn't update watch later or watch history playlist with video, functionality deprecated; try adding videos to a different playlist
[...]
Feb 4, 2024, 6:15:19 AM	Info	Couldn't update watch later or watch history playlist with video, functionality deprecated; try adding videos to a different playlist
Feb 4, 2024, 6:15:20 AM	Info	Couldn't update watch later or watch history playlist with video, functionality deprecated; try adding videos to a different playlist
Feb 4, 2024, 6:15:20 AM	Info	Couldn't update watch later or watch history playlist with video, functionality deprecated; try adding videos to a different playlist
Feb 4, 2024, 6:15:20 AM	Info	Added 0 video(s) to playlist. Error for 104 video(s).
Feb 4, 2024, 6:15:20 AM	Info	Row: 6
Feb 4, 2024, 6:15:20 AM	Info	Row: 7
Feb 4, 2024, 6:15:20 AM	Info	Row: 8
Feb 4, 2024, 6:15:20 AM	Info	Row: 9
Feb 4, 2024, 6:15:20 AM	Info	Row: 10
Feb 4, 2024, 6:15:20 AM	Info	Row: 11
Feb 4, 2024, 6:15:20 AM	Error	Error: 104 video(s) were not added to playlists correctly, please check Debug sheet. Timestamps for respective rows has not been updated.
    at updatePlaylists(Code:195:11)`

**Comment by Elijas** [comment]
As a temporary quickfix you could create a new empty “watch later” playlist
that is not the official Watch Later playlist

**Comment by victorjzsun** [comment]
We are limited by YouTube's Data API so that's not something we can fix. Try the solution above if possible.
