### ISSUE TITLE
TypeError: Cannot read property "items" from undefined.

### ISSUE THREAD

**Issue by senpl** [Elijas/auto-youtube-subscription-playlist-2#17]
Seems like working, but only date is updated and error appears.
For keystring: PL1YG9ktx9sVfaeZtTh0riY1nOrHkWaj6c it produce that error.
Of more info needed let me know.
```
XHR finished loading: POST "https://docs.google.com/spreadsheets/u/0/d/1YjauQJ8HCsnfHcb6GBUV33MpRMVYm70pthcLLV0UFso/scripts/invoke?ruid=221&id=ZZZZZZZZZZZ&lib=M2zyjyQPfO10gQct8sMcXmj5r6QE2Pvz2&func=insideUpdate&ctx=%7B%22gid%22%3A%220%22%2C%22scol%22%3A2%2C%22ecol%22%3A3%2C%22srow%22%3A3%2C%22erow%22%3A4%7D&usit=1&sid=2297dc458b0a1a14&c=1&w=1&smv=33&token=ZZZZZZZZZZZ&includes_info_params=true".
p.send @ 720521041-ritz_waffle_i18n_core__pl.js:321
KR.Wfa @ 720521041-ritz_waffle_i18n_core__pl.js:4224
wm.send @ 720521041-ritz_waffle_i18n_core__pl.js:479
p.OPb @ 720521041-ritz_waffle_i18n_core__pl.js:4153
p.send @ 720521041-ritz_waffle_i18n_core__pl.js:4152
lUb.N3 @ 720521041-ritz_waffle_i18n_core__pl.js:4228
p.Ae @ 720521041-ritz_waffle_i18n_core__pl.js:477
p.mLa @ 4080546244-ritz_waffle_i18n_ritzmaestro__pl.js:113
p.kPb @ 4080546244-ritz_waffle_i18n_ritzmaestro__pl.js:126
wqa @ 720521041-ritz_waffle_i18n_core__pl.js:436
zjc @ 2995667118-ritz_waffle_i18n_postshellbase__pl.js:20
MDd @ 4080546244-ritz_waffle_i18n_ritzmaestro__pl.js:126
p.hob @ 4080546244-ritz_waffle_i18n_ritzmaestro__pl.js:137
p.jK @ 720521041-ritz_waffle_i18n_core__pl.js:602
p.xc @ 720521041-ritz_waffle_i18n_core__pl.js:606
(anonymous) @ 720521041-ritz_waffle_i18n_core__pl.js:1093
Zca @ 720521041-ritz_waffle_i18n_core__pl.js:100
p.dispatchEvent @ 720521041-ritz_waffle_i18n_core__pl.js:98
p.Qh @ 720521041-ritz_waffle_i18n_core__pl.js:844
p.Jo @ 720521041-ritz_waffle_i18n_core__pl.js:843
p.Jo @ 720521041-ritz_waffle_i18n_core__pl.js:850
p.mY @ 720521041-ritz_waffle_i18n_core__pl.js:953
Xca @ 720521041-ritz_waffle_i18n_core__pl.js:95
Tca @ 720521041-ritz_waffle_i18n_core__pl.js:96
c @ 720521041-ritz_waffle_i18n_core__pl.js:2402
(anonymous) @ 720521041-ritz_waffle_i18n_core__pl.js:92
4080546244-ritz_waffle_i18n_ritzmaestro__pl.js:112`
Google Apps Script: TypeError: Cannot read property "items" from undefined.

**Comment by senpl** [comment]
After language change to english error look like that:
`XHR finished loading: POST "https://docs.google.com/spreadsheets/d/1YjauQJ8HCsnfHcb6GBUV33MpRMVYm70pthcLLV0UFso/scripts/invoke?ruid=221&id=ZZZZZZZZZZZ&lib=M2zyjyQPfO10gQct8sMcXmj5r6QE2Pvz2&func=insideUpdate&ctx=%7B%22gid%22%3A%220%22%2C%22scol%22%3A0%2C%22ecol%22%3A1%2C%22srow%22%3A0%2C%22erow%22%3A1%7D&usit=1&sid=3ea589917286f36c&c=1&w=1&smv=33&token=ZZZZZZZZZZZ&includes_info_params=true".
p.send @ 3506810376-ritz_waffle_i18n_core.js:321
JR.Vfa @ 3506810376-ritz_waffle_i18n_core.js:4135
wm.send @ 3506810376-ritz_waffle_i18n_core.js:479
p.OPb @ 3506810376-ritz_waffle_i18n_core.js:4064
p.send @ 3506810376-ritz_waffle_i18n_core.js:4063
kUb.M3 @ 3506810376-ritz_waffle_i18n_core.js:4139
p.Ae @ 3506810376-ritz_waffle_i18n_core.js:477
p.lLa @ 3457819461-ritz_waffle_i18n_ritzmaestro.js:110
p.kPb @ 3457819461-ritz_waffle_i18n_ritzmaestro.js:123
wqa @ 3506810376-ritz_waffle_i18n_core.js:436
yjc @ 1026613991-ritz_waffle_i18n_postshellbase.js:20
FDd @ 3457819461-ritz_waffle_i18n_ritzmaestro.js:123
p.hob @ 3457819461-ritz_waffle_i18n_ritzmaestro.js:133
p.iK @ 3506810376-ritz_waffle_i18n_core.js:597
p.xc @ 3506810376-ritz_waffle_i18n_core.js:601
(anonymous) @ 3506810376-ritz_waffle_i18n_core.js:1081
Zca @ 3506810376-ritz_waffle_i18n_core.js:100
p.dispatchEvent @ 3506810376-ritz_waffle_i18n_core.js:98
p.Qh @ 3506810376-ritz_waffle_i18n_core.js:832
p.Jo @ 3506810376-ritz_waffle_i18n_core.js:831
p.Jo @ 3506810376-ritz_waffle_i18n_core.js:838
p.lY @ 3506810376-ritz_waffle_i18n_core.js:941
Xca @ 3506810376-ritz_waffle_i18n_core.js:95
Tca @ 3506810376-ritz_waffle_i18n_core.js:96
c @ 3506810376-ritz_waffle_i18n_core.js:2341
(anonymous) @ 3506810376-ritz_waffle_i18n_core.js:92
3457819461-ritz_waffle_i18n_ritzmaestro.js:109 `

**Comment by senpl** [comment]
So if in list string: PL1YG9ktx9sVfaeZtTh0riY1nOrHkWaj6c not exist all works for me, but when it is present it produce js errors "items" not defined.

**Comment by magnusv0s** [comment]
i'm getting this error too whenever I try to add a playlist, it works fine with whole channels but not specific playlists from those channels

**Comment by dudemario** [comment]
Related to #25, that playlist doesn't exist on YT

**Comment by victorjzsun** [comment]
Updated script to correctly pull videos from playlists, so closing this issue
