### ISSUE TITLE
Some channels work only after hotfix in editor

### ISSUE THREAD

**Issue by senpl** [Elijas/auto-youtube-subscription-playlist-2#18]
Some channels (eg. UC6Iaz96RkYE-MOjnq5NPgqw) work only after hotfix in editor. This may have something to do with 

> if (e.parameter.update == "True") {

Because when it is commented all is updated as expected, but with this line update is not performed. This work on channels with playlist in them, but for this without that line make's error

updatePlaylists | Bad value (line 17, file "Code")

**Comment by dudemario** [comment]
That bad value actually occurs because you haven't changed or incorrectly typed the spreadsheet's ID on line 17, char 98. If you comment out that line, it uses the ID from line 10. Just add your ID to line 17 and you shouldn't need to change that line anymore.

**Comment by victorjzsun** [comment]
Not sure if this issue is still relevant being quite outdated and the provided channel works without any hotfix for me. Could you provide an update?

**Comment by victorjzsun** [comment]
Closing this as stale
