### ISSUE TITLE
Script fails if video gets deleted while script runs

### ISSUE THREAD

**Issue by Fabian42** [Elijas/auto-youtube-subscription-playlist-2#22]
I just got a mail with this error:
`Document 1eNL_C5WZZSiM5ULX3hvikaK9pqPKdKfKATZ0Znxqric is missing (perhaps it was deleted?) (line 17, file "Code")`
I suspect that means that a new video was detected by the script, then deleted by the uploader and then the script tried to add it to my playlist.
Worst case scenario: In a playlist that allows duplicates, all videos that the script had already handled before the error would be added twice.

**Comment by Fabian42** [comment]
...and it actually did add a duplicate for me.

**Comment by JesperDramsch** [comment]
I believe this has been addressed by the better error handling we implemented @victorjzsun and can be closed.

I had this error a couple days ago and the script ran to completion.

**Comment by victorjzsun** [comment]
Closing due to outdated issue
