### ISSUE TITLE
Seems to skip (some?) videos that are uploaded while the channel is streaming

### ISSUE THREAD

**Issue by Fabian42** [Elijas/auto-youtube-subscription-playlist-2#24]
This channel has a 24/7 music stream: https://www.youtube.com/user/epicmusicvn/videos
But they also upload regular videos. Recently one video got added to my playlist, but two days ago one was skipped.
The most logical explanation seems to be that the script ignores everything as long as a stream is running so that it doesn't keep adding old, deleted streams. And that the channel had a brief stream pause when it published one of the videos, but not for the other. But I don't know for sure.

**Comment by Fabian42** [comment]
Recently it get all videos, even though the channel is still streaming. Maybe something changed, maybe it was just some problem on YouTube's side that caused the issue last time, maybe there's a probability to it. I'll keep testing.

**Comment by dudemario** [comment]
@Fabian42 any updates?

**Comment by Fabian42** [comment]
Oh, I totally forgot about this report, thanks for reminding me. A different channel that is streaming 24/7 has had all of its videos added to the playlist perfectly so far, so this issue is either resolved or it was something else all along.
