### ISSUE TITLE
Fails if playlist is deleted

### ISSUE THREAD

**Issue by Fabian42** [Elijas/auto-youtube-subscription-playlist-2#25]
The last successful run on 1.8.2018 at 4:35, since then every hourly run gives this error message for the `updatePlaylists` function:
`TypeError: Cannot read property "items" from undefined. (line 169, file "Code")`
Sadly Google Sheets doesn't give any more output than that.

**Comment by Elijas** [comment]
Sadly, I currently don't have time available to investigate/fix, but I might check and merge a PR (while putting the person to a list of contributors, of course:))

**Comment by Fabian42** [comment]
Sadly I'm not at all familiar with JavaScript and especially not with the
YouTube API (and an API call seems to be what's wrong here, since
apparently "YouTube.PlaylistItems.list" returns an empty response).
I rely pretty much on this thing, but I have a backlog anyway, the biggest
problem would probably be the 300 video limit as soon as it does work
again. What do you think when you might be able to fix it? A week, a month,
a year?

**Comment by Elijas** [comment]
I currently have to make my financial ends meet, so I really can't say. I'm sorry 😞 

What are the options, then? Well, someone could post a bounty on [Bountify.co](https://bountify.co/) (If you do so, please post the link of it in a comment of this issue).

As for longer-term, if the community expresses a dire need for the project to be supported, I could set up a Patreon account and we could work this out together! 👍

**Comment by Elijas** [comment]
I currently have to make my financial ends meet, so I have to work on other projects. Therefore, I really can't say. I'm sorry 😞

What are the options, then? Well, someone could post a bounty on Bountify.co (If you do so, please post the link of it in a comment of this issue).

Alternatively you could formulate a question on StackOverflow, like it was done here or here (same as above, please link it here)

As for longer-term, if the community expresses a dire need for the project to be supported, I could set up a Patreon account and we could work this out together! 👍

**Comment by Elijas** [comment]
I currently have to make my financial ends meet, so I have to work on other projects. Therefore, I really can't say. I'm sorry 😞

What are the options, then? Well, someone could post a bounty on [Bountify.co](https://bountify.co/) (If you do so, please post the link of it in a comment of this issue).

Alternatively you could formulate a question on StackOverflow, like it [was done here](https://stackoverflow.com/questions/48867365/google-script-auto-add-recently-uploaded-yt-videos-from-subscriptions-to-speci)or [here](https://stackoverflow.com/questions/31161293/deleting-a-video-from-a-playlist-with-youtube-data-api-v3-in-google-apps-script). (Same as above, please questions in the comments).

As for longer-term, if the community expresses a dire need for the project to be supported, I could set up a Patreon account and we could work this out together! 👍

**Comment by Fabian42** [comment]
Since you didn't do any of the things I suggested, I at least made an edit suggestion for README.md that tells the user to fix their playlist IDs: https://github.com/Elijas/auto-youtube-subscription-playlist-2/compare/master...Fabian42:patch-3

**Comment by dudemario** [comment]
I can probably add a couple of checks to search YouTube for missing playlists (YouTube.Playlists.list) and channels (YouTube.Channel.list) and produce a proper error message.

**Comment by JesperDramsch** [comment]
Possibly adressed in #46

**Comment by victorjzsun** [comment]
Closing this after adding new logs to script
