### ISSUE TITLE
Script constantly reaches Youtube API Quota

### ISSUE THREAD

**Issue by Infam** [Elijas/auto-youtube-subscription-playlist-2#28]
I find that the script fails to update my playlists because the quota is exceeded.
![chrome_2019-01-31_11-51-29](https://user-images.githubusercontent.com/14365765/52077681-cdaf3800-254e-11e9-964a-eaaccd2824da.png)
Is there any way to bypass this daily limit or do I just have to deal with it?

**Comment by Fabian42** [comment]
You can't set it to faster than hourly, otherwise you'll always hit rate
limits.

**Comment by Infam** [comment]
Was there a previous version of this script that used API Keys? Previously I never had any problem with quotas, but ever since I updated the spreadsheet, I'm running into problems.

**Comment by JesperDramsch** [comment]
@Infam Did you ensure in: https://github.com/Elijas/auto-youtube-subscription-playlist-2#set-up-instructions
>     2. Allow the Sheets to access Youtube:
>       - Open the `Script Editor` (in menu: `Tools` / `Script Editor...`) of the Sheet
>           - In menu: `Resources` / `Advanced Google Services`
>           - Scroll down and make sure `YouTube Data API` is enabled
>           - Then, `Google Developers Console` / `Youtube Data API` / `Enable API`, close the tab, go back to Script Editor and click `OK`
>           - Continue only after the yellow `Updating Google Services` box disappears in the top of the Script Editor
>       - Close the Developers Console and Script Editor, open the Sheet again
>           - In menu: `Functions` / `Update Playlists`
>           - Grant access in the dialog

**Comment by zpxociq** [comment]
I struggled with same error and I am not able to follow the step of going to 'Google Developers Console' from script editor. I don't see such option anywhere on script editor or under advanced Google services. So I directly google and reached 'Google Developers Console' and enabled API but they asked me to create credentials which I wasn't sure of. 
So at this stage although API is enabled inside Youtube Data API, I get the quota overflow error.

**Comment by nbcartier** [comment]
^ bump. I was faced with the same error as "zpxociq"

**Comment by victorjzsun** [comment]
I'm not sure if anyone is still monitoring this thread for changes, but I have reduced the quota calls with the newest release. Please make a copy of the sheet again, follow the setup instructions, and let me know if you're still having quota issues. Remember, you cannot add 200 (or close to) videos on the same day using this script.

**Comment by JesperDramsch** [comment]
Just ran into the same issue when copying a new spreadsheet and authorizing it.

I cannot figure out how to add the new spreadsheet to the Google Dev Console and increase the Youtube API quota.

**Comment by victorjzsun** [comment]
@JesperDramsch It's a weird process as explained [here](https://developers.google.com/apps-script/guides/cloud-platform-projects). A sheet-bound script has an automatically-created default Google Cloud Platform (GCP) project that you can't see nor modify. It automatically gets access to the APIs required as well. In order to manage the project yourself, you need to [migrate the script to a standard GCP project](https://developers.google.com/apps-script/guides/cloud-platform-projects#switching_to_a_different_standard_gcp_project). Once you've set up the script to use a standard project, you can view quotas and usage. However, from what I've tried, you can't increase the quota without having to go through a whole application process.

**Comment by JesperDramsch** [comment]
I see, so effectively new users have to turn down the update frequency to make this work.

**Comment by victorjzsun** [comment]
Doesn't look like anyone is still having quota issues that we can address so will close due to inactivity
