### ISSUE TITLE
Duplicates

### ISSUE THREAD

**Issue by Ashtopher** [Elijas/auto-youtube-subscription-playlist-2#3]
When updating I get duplicates of videos, and some videos from the subscription feed are skipped/not included in the automated playlist.

**Comment by Elijas** [comment]
If you have same channels and/or ALL keyword in a row, this is suspected. 
There may be some issues with timestamp (too early - includes too much, too late - too little). Are there any patterns in tbe skipped videos? 
Any other info? Screenshot of the sheet before/after update ? For privacy reasoms, if you care, you can color over/pixelate the channel names

**Comment by Ashtopher** [comment]
I'm not entirely sure, but the duplicates seem to be descending (e.g. 4 copies, then 3 copies, then 2 copies, etc.) I have over 1000 subscriptions, so the feed updates pretty fast - maybe that's why? I haven't tested adding in individual channels to the subfeed to slow the speed. Also as you can see, the videos added aren't in the correct order as well. I will try to test this on a different account and see if it is a problem with the number of subscriptions, or my subaccounts (I have 3 accounts within the Google ID).

Spreadsheet: http://i.imgur.com/Z0yvFAK.png
Playlist: https://www.youtube.com/playlist?list=PLcugqZdiV9og5abn6BN_8m3pHqKKN4lYp
Sub feed: http://i.imgur.com/OxFqIDB.png

**Comment by Elijas** [comment]
How often is the script run?

**Comment by Ashtopher** [comment]
Once an hour, sometimes you see the duplicate videos interweave in a (x)(y)(x)(y) pattern.

**Comment by y2kbugger** [comment]
bet you are hitting a race condition. slow down the frequency that you run it.
