### ISSUE TITLE
UTC Issue

### ISSUE THREAD

**Issue by bobpiesz** [Elijas/auto-youtube-subscription-playlist-2#35]
I realize that the UTC is not GMT, but I tried changing the UTC offset to R (eastern standard), instead of it being set to Z, and nothing fixes my issue.

The issue: I believe the timestamp is ahead of time from the youtube video upload time, as if I change the timestamp back several hours, it fixes the issue.

Any ideas?

function ISODateString(d) { // modified from src: 
http://stackoverflow.com/questions/7244246/generate-an-rfc-3339-timestamp-similar-to-google-tasks-api
 function pad(n){return n<10 ? '0'+n : n}

 return d.getUTCFullYear()+'-'
      + pad(d.getUTCMonth()+1)+'-'
      + pad(d.getUTCDate())+'T'
      + pad(d.getUTCHours())+':'
      + pad(d.getUTCMinutes())+':'
      + pad(d.getUTCSeconds())+'.000R'

**Comment by bobpiesz** [comment]
.000Z switched to .000R does not fix the time offset issue.

**Comment by victorjzsun** [comment]
Should be fixed with #67 so closing this issue. Please reopen if this is still an issue.
