### ISSUE TITLE
Pull spreadsheet id on onOpen call

### ISSUE THREAD

**Issue by dudemario** [Elijas/auto-youtube-subscription-playlist-2#40]
Prevent users from forgetting to change the id, better to do it automatically.
Since the link to spreadsheet automatically opens it, this script will be guaranteed to run at least once.

Or maybe another alternative on when to pull id?

**Comment by Elijas** [comment]
Could you write me an email I'd like to discuss something with you

**Comment by Elijas** [comment]
(off-topic) 
@dudemario Would you consider becoming a collaborator for this repository? My time is very limited, but I'd love to see this project thrive. 

Write me an email, if you'd accept.
