### ISSUE TITLE
Create releases

### ISSUE THREAD

**Issue by deepfriedmind** [Elijas/auto-youtube-subscription-playlist-2#43]
Please create releases when changes have been made.

**Comment by Elijas** [comment]
Did you mean github release functionality? Since the app is not downloadable (does not need to be compiled), I think commit history might be enough if someone would want to roll back their version.

But we're open for counter arguments and suggestions:)

**Comment by deepfriedmind** [comment]
My counter argument is that releases can be _watched_, so followers could get an email when a new version is released :)

**Comment by Elijas** [comment]
Fair point.

@dudemario Would you agree to create a release every time the main .gs file is updated?

Since releases would be used for notifications, we could use the current date as the only content for the release

**Comment by dudemario** [comment]
Sure, sounds good.

This will basically happen whenever there's a merge to master concerning the .gs file right? Shouldn't be too hard.

**Comment by deepfriedmind** [comment]
That's great, thank you!

**Comment by Elijas** [comment]
@dudemario Exactly! Thanks
