### ISSUE TITLE
Can't update by playlist ID

### ISSUE THREAD

**Issue by Jay1146** [Elijas/auto-youtube-subscription-playlist-2#55]
I managed to get new videos from channels, but when I do the same with playlists ID I get this error:

`Cannot search YouTube, ERROR: Message: [API call to youtube.search.list failed with error: Invalid channel.] Details: {"message":"Invalid channel.","code":400,"errors":[{"domain":"youtube.search","reason":"invalidChannelId","message":"Invalid channel.","locationType":"parameter","location":"channelId"}]}`

Tried both playlists from my account and different users, same results. I haven't seen people mention this unless I'm doing something wrong. Also I'm using a YouTube account from back in the day.

**Comment by victorjzsun** [comment]
Thanks, will get this fix merged asap
