### ISSUE TITLE
Just a typo on the app...

### ISSUE THREAD

**Issue by Kabyl** [Elijas/auto-youtube-subscription-playlist-2#8]
I literally found this like 5 minutes ago (yougather.xyz) and i'm super excited to give this a try.

I found a typo... when the page is loading, it says:

Found 473 channels.
Playlists using **_subscritptions_** will be updated accordingly.

Thanks!

**Comment by Elijas** [comment]
We love to hear you liked!

Fixed the typo, thanks! Any feedback is always welcome!
