### ISSUE TITLE
Script successfully finished, but no video's added to playlist

### ISSUE THREAD

**Issue by Nickske92** [Elijas/auto-youtube-subscription-playlist-2#81]
So the script itself says that it ran successfully and that it added a couple of video's, but when I look at my watch later playlist, there are no video's added. I tried the older and updated version of the script, but I got the same result. Also my watch later playlist says that it updated today.
![1](https://user-images.githubusercontent.com/72335997/95010886-26d94400-062d-11eb-9967-9068dc3dca44.jpg)
![2](https://user-images.githubusercontent.com/72335997/95010889-280a7100-062d-11eb-9051-3bf438aa98c3.jpg)
![3](https://user-images.githubusercontent.com/72335997/95010890-28a30780-062d-11eb-9b26-3ea19ef90955.jpg)
![4](https://user-images.githubusercontent.com/72335997/95010891-293b9e00-062d-11eb-9805-936e3933ca97.jpg)

**Comment by victorjzsun** [comment]
Can you try on a non-watchlist playlist?

**Comment by victorjzsun** [comment]
I also realized I didn't update the script to the newest version so I'd recommend making a copy of the script again to get the latest version

**Comment by Nickske92** [comment]
> 
> 
> I also realized I didn't update the script to the newest version so I'd recommend making a copy of the Google Sheet again to get the latest version

Thanks for your fast reply! I tried it with the new updated script (I named it 2.0 in sheets), but I still got the same result, no video's added in the watch later playlist.
Then I tried the script on another playlist, but then I got the error message 403?

![1](https://user-images.githubusercontent.com/72335997/95026309-cbd93880-0690-11eb-9cdb-579484308ba8.jpg)
![2](https://user-images.githubusercontent.com/72335997/95026311-cd0a6580-0690-11eb-9f3d-1efb435c74ae.jpg)
![3](https://user-images.githubusercontent.com/72335997/95026312-cda2fc00-0690-11eb-8004-004e6acea3b3.jpg)
![4](https://user-images.githubusercontent.com/72335997/95026313-ce3b9280-0690-11eb-9214-e1ec8b198ed4.jpg)
![5](https://user-images.githubusercontent.com/72335997/95026314-cf6cbf80-0690-11eb-878a-717c7f1357f2.jpg)

**Comment by victorjzsun** [comment]
Hm, so it says the script doesn't have access to the playlist. Are you sure you're using the same account for both Google Sheets and YouTube? There's currently no support for brand accounts. Also check that you spelled the playlist's ID correctly.

**Comment by victorjzsun** [comment]
If it looks right to you, can you try the following test:
1. Within the sheet, open the script editor `Tools -> Script Editor`
2. Paste the following line of code on any empty line: `function test() {results=YouTube.Channels.list('snippet', {mine:true});Logger.log(results.items[0].id)}`
3. Save `File -> Save`
4. Run the test `Run -> Run function -> Test`
5. View log `View -> Logs` This should produce a timestamp and a channel id `UC~~~~~~~~~`
6. Navigate to `www.youtube.com/channel/<CHANNELID>` replaced with the result from 5.
7. This should be your channel and should list the playlist you're trying to add the videos to.

**Comment by Nickske92** [comment]
> 
> 
> Hm, so it says the script doesn't have access to the playlist. Are you sure you're using the same account for both Google Sheets and YouTube? There's currently no support for brand accounts. Also check that you spelled the playlist's ID correctly.

So that was the problem. I was using a Brand account. I tried the script with another normal google account and now everything works! Thanks!
