### ISSUE TITLE
Script updatePlaylists experienced an error

### ISSUE THREAD

**Issue by MTShelll** [Elijas/auto-youtube-subscription-playlist-2#85]
When running Update Playlist function as usual, after 3-4 seconds of running the script get an error: Script updatePlaylists experienced an error. I didn't change anything and it was running well for more than a year prior. Anyone with similar issue?

**Comment by Fabian42** [comment]
What's on the debug sheet?

**Comment by MTShelll** [comment]
I completely re-did the google doc with new script and new playlist and it worked. Don't know what was the issue. I will mark this as solved.
