### ISSUE TITLE
Playlist has a large ammount of repeated videos

### ISSUE THREAD

**Issue by TheFip** [Elijas/auto-youtube-subscription-playlist-2#87]
Hello! I have run in to an error where videos get added multiple times in the same playlist.

For some reason this only happened in one of the four playlist I have created. I have tried to recreate this playlist multiple times, but sadly this error eventually always happened again.

So, I assume it has something to do with the list of channels for this playlist?

I really don’t know, is there anyway to solve this problem?

**Comment by Fabian42** [comment]
Is there something in the debug sheet? If the script adds one video to the playlist and then fails on a later video, then it doesn't update the timestamp and adds the same video again on the next run.

**Comment by TheFip** [comment]
Thank you for the fast reply!
It does have a something on the bug sheet for that row actually, it reads as follows:

> Couldn't` update playlist with video (zJJa-p9U0oc), ERROR: Message: [API call to youtube.playlistItems.insert failed with error: Video not found.] Details: {"message":"Video not found.","code":404,"errors":[{"message":"Video not found.","reason":"videoNotFound","domain":"youtube.playlistItem"}]}

I guess its trying to insert  private video on the playlist, and causing an error cause of that? 
If so, how could i solve this issue?

**Comment by victorjzsun** [comment]
Similar issue with private videos here: https://github.com/Elijas/auto-youtube-subscription-playlist-2/issues/74. I add a workaround to ignore these errors

**Comment by victorjzsun** [comment]
@TheFip I made the change to the spreadsheet's script, either use http://bit.ly/subscriptionPlaylistsCopy to create a new copy of the sheet or copy the script from [GitHub](https://raw.githubusercontent.com/Elijas/auto-youtube-subscription-playlist-2/master/sheetScript.gs) and paste it into your sheet's code editor. Let me know if the issue is fixed, thanks!

**Comment by Fabian42** [comment]
So is #74 fixed then?

**Comment by TheFip** [comment]
The new script worked as far as i can tell! Thank you so much!
