### ISSUE TITLE
Logging into yougather.xyz results in a server error.

### ISSUE THREAD

**Issue by RyanMadsen** [Elijas/auto-youtube-subscription-playlist-2#9]
Here is an image what I see. The right part on the page shows up after I click reload channels in the menu. The left side repeats the error when I try to reload the playlists. This is my first time logging into this site, but I have created a subscriptionPlaylists google sheet copy and tried it there. I wanted to see how it would work on the site, but I can't do anything currently.
<img width="1169" alt="screen shot 2016-09-28 at 12 00 07 pm" src="https://cloud.githubusercontent.com/assets/7959773/18924052/5afd9a3a-8574-11e6-9eb1-f70994fa9b33.png">

**Comment by Elijas** [comment]
It probably relates to https://github.com/Elijas/auto-youtube-subscription-playlist-2/issues/10
