### ISSUE TITLE
403 forbiden

### ISSUE THREAD

**Issue by dolfijn3000** [Elijas/auto-youtube-subscription-playlist-2#93]
whenever i run the script i get this error:
> Couldn't update playlist with video (F6Mt7XpYVEo), ERROR: Message: [API-aanroep aan youtube.playlistItems.insert is mislukt als gevolg van fout: Forbidden] Details: {"errors":[{"domain":"youtube.playlistItem","reason":"playlistItemsNotAccessible","message":"Forbidden"}],"code":403,"message":"Forbidden"}

does someone know how to fix this

**Comment by Fabian42** [comment]
Just to make sure: Do you have anything related to a "brand account"? #51

**Comment by dolfijn3000** [comment]
it turns out i was using a brand account. i used an ohter account that was not a brand account isntead.

**Comment by victorjzsun** [comment]
I'll close this then since you found a solution. Can't support brand accounts yet, unfortunately.
